### ISSUE TITLE
get errors when trying to start custom opk

### ISSUE THREAD

**Issue by furesoft** [Harteex/OpenPackageCreator#2]
ill get tons of errors, when trying to start my opk. 
unable to open opk,
unable to open icon
and so on, the application closed so quickly that i cant read all errors

**Comment by Harteex** [comment]
If I would guess, the most likely reason is a problem with your desktop file.
Please write the content of your .desktop file, or even better, upload your opk somewhere. Then it will be easier to figure out what's wrong with it.

**Comment by furesoft** [comment]
here is my opk-file: http://furesoft.bplaced.net/share/dotnet-test.opk

**Comment by Harteex** [comment]
The actual OPK file is fine, I unpacked and repacked and got an identical OPK file (apart from the modified date in the squashfs header).

The first thing I noticed was that the icon was too large. At least for the GCW Zero, the icon is supposed to be 32x32. It seems like you target the RG350 though, which might do things differently, I don't know. I don't think that causes the problems though.

The executable appears to be for ARM, not for MIPS (which the RG350 and GCW Zero both are). Maybe this causes your problems? I would recommend you try to launch your application directly, without packing it as an OPK, and ensure that it runs first. Copy over your files to your device, run the Terminal application on the device, and then login with SSH and launch your application through that.

If you need additional support, the Dingoonity forums or the #opendingux IRC channel on Freenode might be good options.
