### ISSUE TITLE
If StartupNotify=true is included, the app cannot be edited.

### ISSUE THREAD

**Issue by haveanair1** [Harteex/OpenPackageCreator#3]
App if StartupNotify=true is included
New save doesn't work.
Can I add items so I can edit and save them?

**Comment by Harteex** [comment]
For now you will have to use the option "Use existing as is" and edit your desktop file manually.

If I have some extra time I might add support for editing extra/unknown keys.

**Comment by haveanair1** [comment]
Thank you very much for your quick reply. I hope and wait.

**Comment by Harteex** [comment]
Is it enough if fields such as StartupNotify are retained, but not editable in the app?
So if you load a folder with an existing desktop file, StartupNotify will be kept when saving.

Or do you need it to be editable?

**Comment by haveanair1** [comment]
I hope you can edit it to change the title, path and icon.

**Comment by Harteex** [comment]
Please try the 1.1.3 version that was just released

**Comment by haveanair1** [comment]
thank you so much

**Comment by haveanair1** [comment]
Do you have an rg350 series game console? I would like to share the opk app that I thought had a problem.
App if StartupNotify=true is included
New save didn't work. So, I thought there was a cause of StartupNotify=true, so I commissioned it. Thankfully it didn't work when I changed the title and icon and saved it with the new version I made to keep the StartupNotify=true command. The cause seems to be something else.
https://drive.google.com/file/d/1szA_6m6oa5CLboWmk5s2zetLz1a1808P/view?usp=sharing
https://drive.google.com/file/d/1EpjZtczkhpNDJk0JkjYU4C2SgOKveCds/view?usp=sharing

**Comment by Harteex** [comment]
Unfortunally I do not have an rg350.

Did the app work originally, and then after editing it stop working?
Or did the app never work at all?

If it stopped working after you edited it, could you send a link to the working app and the non-working app after you edited it. So I can compare them.
